### ISSUE TITLE
Use ES6 module import syntax instead of the require syntax

### ISSUE THREAD

**Issue by paales** [ben-eb/caniuse-lite#15]
I was trying to use the library in a new project which leverages the new modules tag: https://caniuse.com/#feat=es6-module (in combination with webcomponents). Wanted to build some project with this library, but it seems this project is using the old require() syntax.

**Comment by ben-eb** [comment]
@ai Any thoughts?

**Comment by andyjansson** [comment]
Sounds to me like he's not using webpack.

**Comment by ai** [comment]
You can use `require()` in any Node.js module, so having ES modules will give only a more cute syntax, but not a real use case.

In webpack ES modules will be able to use tree-shaking, but I am not sure, that it will give any benefits for `caniuse-lite` API.

So, since we are talking only about syntax sugar, if we have a way to provide both CommonJS and ES Modules syntax without any extra problems, so why not? Unfortunately, I am not sure how to provide both syntaxes without having 2 copies of every data file, which will bloat package size.

This is my raw thoughts :D. @paales do you have a plan of adding ES modules syntax support here?

**Comment by paales** [comment]
Never responded to this ticket...  sorry! @andyjansson was right, wasn't using webpack, was using a very minimal build system which had an almost empty build step (only path resolution), which caused this to not work.

I would guess that since es6 modules are now the standard, you should be able to convert te complete project to it? :)

**Comment by ai** [comment]
> you should be able to convert te complete project to it? :)

I think it is trends driven development, which is not so good.

We always should change technologies only because they are giving benefits, not because it is a trend now.
