### ISSUE TITLE
Way to load agents and region separatly

### ISSUE THREAD

**Issue by ai** [ben-eb/caniuse-lite#8]
With Size Limit I found, that when I import simple function:

```js
var region = require('caniuse-lite').region
```

I import a huge `caniuse-lite/data/features/*`.

My main concern that importing many unnecessary files will loose resources on JS parsing.
Maybe we can add API like:

```js
var agents = require('caniuse-lite/agents')
var region = require('caniuse-lite/region')
```

It will not break public API.

**Comment by ben-eb** [comment]
This is because the unpacker code is [rolled up](http://rollupjs.org/) into a single bundle, which does eliminate some redundancy at the cost of extra parsing; as I understood it we were using all this data  so it's fine? But anyway if this is not acceptable I am happy to accept a pull request for this, note that it will not affect the existing publish process - you only need to update the `prepublish` script (and swap out rollup for something else or adjust its config).

**Comment by ai** [comment]
OK, I will make PR with:

1. Moving all unpacker functions to separated files.
2. Importing these files in `index.js` to provide the same API.

Where should I put these files?

**Comment by ben-eb** [comment]
The unpacker code is already in separate files in `src/unpacker`, it's rollup that combines them into a single file. So we need to change the build process from rollup to something else?

**Comment by ai** [comment]
Do we need rollup? :D 

We can create some sort of `src/unpacker/index.js` with:

```js
module.exports = {
  features: require('./features'),
  region: require('./region.js'),
  …
}
```

**Comment by ben-eb** [comment]
Not necessarily, it was about concealing the complexity of needing to unpack related data when consuming the module. 😄

**Comment by ai** [comment]
OK, I will try to create PR tomorrow
